### PR TITLE
Add a BOM for Vaadin Spring

### LINKED ISSUE #153: Create a BOM for Vaadin Spring
To avoid problems where a transitive dependency brings a different version of vaadin-spring than what e.g. vaadin-spring-boot-starter expects, there should be a BOM for Vaadin Spring.

Spring Initializr (start.spring.io) should be updated to use the BOM when this ticket is resolved.

### PR DESCRIPTION
**Pull request by pleku**
Fixes #153

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/159)

### CODE REVIEW

**Comment by hesara** [comment]
The only question I have is whether the starter version should be selected by the BOM in the Spring Initializr created project, or whether the started should depend on the BOM.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/159#-:-KXAOggUq80byB_Rb7MJ:bc3135)*

**Comment by pleku** [comment]
@snicoll you wanted to review / test this with start.spring.io ?

**Comment by pleku** [comment]
Actually starting to think that is not needed, if we add vaadin-spring versions to the vaadin-bom.

**Comment by snicoll** [comment]
@pleku this would have my preference by far. Having a single bom that gives me both the `vaadin` dependencies and the spring support is really what I'd prefer.

**Comment by pleku** [comment]
@snicoll thanks for your input, we have discussed this and have agreed that we should add vaadin-spring (and all our add-ons) to the framework bom.

I'm closing this PR, we will look to add vaadin-spring to vaadin bom as soon as possible, it might take a week or two as we're rather busy with 8 currently.

**Pull request closed without merging**
