### PR TITLE
fix: delegate non-spring beans instantiation to super method

### LINKED ISSUE #732: Spring Boot unable to create an 'com.vaadin.flow.di.LookupInitializer$RegularOneTimeInitializerPredicate'
Start a Spring application with latest Spring and Flow snapshots. See an error:

```
 java.lang.IllegalArgumentException: Unable to create an instance of 'com.vaadin.flow.di.LookupInitializer$RegularOneTimeInitializerPredicate'. Make sure the class has a public no-arg constructor.
```

Build log here:
https://bender.vaadin.com/viewLog.html?buildId=216599&buildTypeId=Flow_Flow70_AddOns_Spring170Snapshot&tab=buildLog

Versions: 
Vaadin: 20.0-SNAPSHOT (2021-03-03)
Flow: 7.0-SNAPSHOT (2021-03-03)
Spring add-on: 17.0-SNAPSHOT (2021-03-03)

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #732

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Requires https://github.com/vaadin/flow/pull/10186

**Review by caalador — APPROVED** [review]

**Comment by caalador** [comment]
```
	[Compiler] Compilation failure
/opt/agent/work/cd0aca6139b3f1ae/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java:[182,20] method instantiate in class com.vaadin.flow.spring.SpringLookupInitializer cannot be applied to given types;
  required: org.springframework.web.context.WebApplicationContext,java.lang.Class<T>,java.lang.Class<?>
  found: java.lang.Class<T>,java.lang.Class<capture#1 of ?>
  reason: cannot infer type-variable(s) T
    (actual and formal argument lists differ in length)
```

**Comment by denis-anisimov** [comment]
> ```
> 	[Compiler] Compilation failure
> /opt/agent/work/cd0aca6139b3f1ae/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java:[182,20] method instantiate in class com.vaadin.flow.spring.SpringLookupInitializer cannot be applied to given types;
>   required: org.springframework.web.context.WebApplicationContext,java.lang.Class<T>,java.lang.Class<?>
>   found: java.lang.Class<T>,java.lang.Class<capture#1 of ?>
>   reason: cannot infer type-variable(s) T
>     (actual and formal argument lists differ in length)
> ```

Flow SNAPSHOT has failed 3 times in a row. There is no SNAPSHOT which has the required method `protected`.
So there is nothing to do here.

**Comment by caalador** [comment]
Right. The exception was a bit strange. :+1:

**Pull request merged**
