### PR TITLE
Get rid of deprecated spring class

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/138)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/spring/138#-KV-p992Sdi5XDW862fr:-KV-p992Sdi5XDW862fs:b-vb11gz) ([raw file](https://github.com/vaadin/spring/blob/72b657bf50ee01e944e06eb37e1e3d2c1b705b30/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L29)):*
> ```Java
> import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
> import org.springframework.boot.context.properties.EnableConfigurationProperties;
> import org.springframework.boot.web.servlet.ServletRegistrationBean;
> ```

this change would actually break our Spring Boot 1.3 compatibility - we might not guarantee compatibility anyway, but I'd perhaps leave this change until later in case someone wants to try to use it with 1.3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/138)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/spring/138#-KV-p992Sdi5XDW862fr:-KV-vCOO7Ouzo_Z0xzvB:b6sq75e) ([raw file](https://github.com/vaadin/spring/blob/72b657bf50ee01e944e06eb37e1e3d2c1b705b30/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> this change would actually break our Spring Boot 1.3 compatibility - we might not guarantee compatibility anyway, but I'd perhaps leave this change until later in case someone wants to try to use it with 1.3
</details>
Master branch fails to compile against latest Spring 3 even without this change. There is no sense keep compatibility here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/138)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/spring/138#-KV-p992Sdi5XDW862fr:-KV-zXC_jtvOrWLK3aYj:bo9ehfp) ([raw file](https://github.com/vaadin/spring/blob/72b657bf50ee01e944e06eb37e1e3d2c1b705b30/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L29)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Master branch fails to compile against latest Spring 3 even without this change. There is no sense keep compatibility here.
</details>
not about Spring 3 but about Spring Boot 1.3, and apart from tests that use new 1.4 features, seems to compile with Boot 1.3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/138)*

**Comment by elmot** [comment]
Postponed

**Comment by elmot** [comment]
Already fixed

**Pull request closed without merging**
