### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/282)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/vaadin/spring/282#-LCZGKCkELWPS_ekzC1Y:-LCZGKCkELWPS_ekzC1Z:bb6llis) ([raw file](https://github.com/vaadin/spring/blob/169df615dbf1ad89a128f91c8cfe7aa5cb0e0040/README.md#L10)):*
> ```Markdown
> * 1.2 for Vaadin Framework V7 versions 
> * 2.1 for Vaadin Framework V8.0.X versions 
> * 3.0 for Vaadin Framework V8.2 versions 
> ```

8.2+

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/282)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/282)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/vaadin/spring/282#-LCZGKCkELWPS_ekzC1Y:-LCn0ofC41zJN1n9efRc:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/169df615dbf1ad89a128f91c8cfe7aa5cb0e0040/README.md#L10)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

8.2+
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/282)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/282)*

**Pull request merged**
