### PR TITLE
Update README for 1.2

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/281)

### CODE REVIEW

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/281#-:-LCYeMPV1idOcl1GhOPP:bnfp4nl)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[README.md, line 8 at r1](https://reviewable.io/reviews/vaadin/spring/281#-LCbnkOR5D30WO2K8ytu:-LCbnkOR5D30WO2K8ytv:b-g5vsbd) ([raw file](https://github.com/vaadin/spring/blob/576d26dbf75ff1704d0322ad8a2abaf2155329a5/README.md#L8)):*
> ```Markdown
> Vaadin Spring is the official Spring integration for [Vaadin Framework](https://github.com/vaadin/framework).
> This branch is Vaadin Framework V7 compatible. See other branches for other framework versions:
> * 2.0 and 2.1 for Vaadin Framework V8.0.X versions 
> ```

8.0 and 8.1

---

*[README.md, line 9 at r1](https://reviewable.io/reviews/vaadin/spring/281#-LCbnicP3Oj9cWdWLbQA:-LCbnicQ-k_SyMZCtFAu:bb6llis) ([raw file](https://github.com/vaadin/spring/blob/576d26dbf75ff1704d0322ad8a2abaf2155329a5/README.md#L9)):*
> ```Markdown
> This branch is Vaadin Framework V7 compatible. See other branches for other framework versions:
> * 2.0 and 2.1 for Vaadin Framework V8.0.X versions 
> * 3.0 for Vaadin Framework V8.2 versions 
> ```

8.2+

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/281)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 8 at r1](https://reviewable.io/reviews/vaadin/spring/281#-LCbnkOR5D30WO2K8ytu:-LCn0IxV0LExoatKWZNv:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/576d26dbf75ff1704d0322ad8a2abaf2155329a5/README.md#L8)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

8.0 and 8.1
</blockquote></details>

Done.

---

*[README.md, line 9 at r1](https://reviewable.io/reviews/vaadin/spring/281#-LCbnicP3Oj9cWdWLbQA:-LCn0JDi-vO5BRZIdNzy:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/576d26dbf75ff1704d0322ad8a2abaf2155329a5/README.md#L9)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

8.2+
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/281)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/281)*

**Pull request merged**
