### PR TITLE
The spring servlet can now handle spring type resources.

### PR DESCRIPTION
**Pull request by caalador**
This will enable us to package spring-boot as a jar.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 148 at r1](https://reviewable.io/reviews/vaadin/spring/317#-LEDgKTf9TYqUjOdJXKA:-LEDgKTf9TYqUjOdJXKB:b4om0b0) ([raw file](https://github.com/vaadin/spring/blob/cf5959e2d35327387240dda01e111b32ad9cf7bf/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L148)):*
> ```
> public InputStream getResourceAsStream
> ```

Is this code (and as a consequence everything else as I understand) really needed at all?
If I understand correctly all those methods are intended to handle web resources when they are asked via HTTP.
`CLASSPATH_RESOURCE_LOCATIONS` are standard locations for static web resources in Spring boot and it should be its responsibility to handle requests properly. 
So it looks really weird that we have to hardcode those Spring boot paths and care about them by ourselves as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 148 at r1](https://reviewable.io/reviews/vaadin/spring/317#-LEDgKTf9TYqUjOdJXKA:-LEDkTkv8adrwBFpcx_L:brun7yf) ([raw file](https://github.com/vaadin/spring/blob/cf5959e2d35327387240dda01e111b32ad9cf7bf/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L148)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> public InputStream getResourceAsStream
> ```

Is this code (and as a consequence everything else as I understand) really needed at all?
If I understand correctly all those methods are intended to handle web resources when they are asked via HTTP.
`CLASSPATH_RESOURCE_LOCATIONS` are standard locations for static web resources in Spring boot and it should be its responsibility to handle requests properly. 
So it looks really weird that we have to hardcode those Spring boot paths and care about them by ourselves as well.
</blockquote></details>

All requests for get resource goes through the `getResource` methods and requesting these files from the servletContext when running spring-boot from a jar will not return a file for us. But updated the functionality so we don't depend on resource strings.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/spring/317#-LEEI4F3-_OsV8LR9u8q:-LEEI4F3-_OsV8LR9u8r:bfm2ktk) (no related file):*
Does it make sense to add any test for it ?

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 148 at r1](https://reviewable.io/reviews/vaadin/spring/317#-LEDgKTf9TYqUjOdJXKA:-LEEHmV_AGY7yNJSyl-p:bqoh4zk) ([raw file](https://github.com/vaadin/spring/blob/cf5959e2d35327387240dda01e111b32ad9cf7bf/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L148)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

All requests for get resource goes through the `getResource` methods and requesting these files from the servletContext when running spring-boot from a jar will not return a file for us. But updated the functionality so we don't depend on resource strings.
</blockquote></details>

Hmm.....
Weird.

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 150 at r2](https://reviewable.io/reviews/vaadin/spring/317#-LEEHSR5Et6mg1WZhBE7:-LEEHSR5Et6mg1WZhBE8:bht9fcu) ([raw file](https://github.com/vaadin/spring/blob/5c9df635d25c4f92ab28d1f02d7511ab332e127b/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L150)):*
> ```
> .replaceAll
> ```

Are you sure that you need `replaceAll` here ?
This method uses regexps.
`replace(CharSequence target, CharSequence replacement)` should be enough. Or not ?

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 172 at r2](https://reviewable.io/reviews/vaadin/spring/317#-LEEGjeR4FN3LwHdKFE8:-LEEGjeS4zS2Jo7gYany:b-v9kn9q) ([raw file](https://github.com/vaadin/spring/blob/5c9df635d25c4f92ab28d1f02d7511ab332e127b/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L172)):*
> ```
>             return context.containsBean(
>                     configurationPrefix + "-" + resourcePropertiesFQN);
> ```

This is quite complicated way to check the bean presence.
As I understand you need `ResourceProperties`  bean.
You may ask `context.getBeanNamesForType()` and check the length of the resulting array.
So no need to use explicit bean name.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/spring/317#-LEEI4F3-_OsV8LR9u8q:-LEEPiWW4amKjDhy_Zyr:b-y8l1m3) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Does it make sense to add any test for it ?
</blockquote></details>

It would, but I don't know what or how.

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 150 at r2](https://reviewable.io/reviews/vaadin/spring/317#-LEEHSR5Et6mg1WZhBE7:-LEEQSvVEGEkkIZE11YV:b-etzd87) ([raw file](https://github.com/vaadin/spring/blob/5c9df635d25c4f92ab28d1f02d7511ab332e127b/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L150)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> .replaceAll
> ```

Are you sure that you need `replaceAll` here ?
This method uses regexps.
`replace(CharSequence target, CharSequence replacement)` should be enough. Or not ?
</blockquote></details>

Done.
Simplified the concatenation to not use replace.

---

*[vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java, line 172 at r2](https://reviewable.io/reviews/vaadin/spring/317#-LEEGjeR4FN3LwHdKFE8:-LEETJbM8Vu7ehHwWPJY:b2nqqzq) ([raw file](https://github.com/vaadin/spring/blob/5c9df635d25c4f92ab28d1f02d7511ab332e127b/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L172)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>             return context.containsBean(
>                     configurationPrefix + "-" + resourcePropertiesFQN);
> ```

This is quite complicated way to check the bean presence.
As I understand you need `ResourceProperties`  bean.
You may ask `context.getBeanNamesForType()` and check the length of the resulting array.
So no need to use explicit bean name.
</blockquote></details>

Thanks that's much better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317#-:-LEElTpp29b7_9RKCvUQ:bnfp4nl)*

**Comment by caalador** [comment]
Dismissed @vaadin-bot from 3 discussions.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/317)*

**Pull request merged**
