### PR TITLE
Remove fw8 source code

### PR DESCRIPTION
**Pull request by denis-anisimov**
The first step for vaadin/flow#3695

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/258)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 84 of 84 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/258)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/258#-:-LADLjc4-nhyZYH47iqE:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[README.md, line 21 at r2](https://beta.reviewable.io/reviews/vaadin/spring/258#-LADLo0Q9T6788d1-Os3:-LADLo0Q9T6788d1-Os4:b9c80qr) ([raw file](https://github.com/vaadin/spring/blob/c9f644f10ad683b02851730e6bc99fffb940aa5d/README.md#L21)):*
> ```Markdown
> 
> 
> Copyright 2015-2017 Vaadin Ltd.
> ```

Should we update the copyright also?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/258)*

**Comment by SomeoneToIgnore** [comment]
Unless you want to update the copyright from 2017 to 2018, feel free to merge.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/258#-:-LADLvDv2aRDt-63tFEs:bvlypvt)*

**Comment by denis-anisimov** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[README.md, line 21 at r2](https://beta.reviewable.io/reviews/vaadin/spring/258#-LADLo0Q9T6788d1-Os3:-LADMh2H7KEZhF-Lo__y:b-4lp7nt) ([raw file](https://github.com/vaadin/spring/blob/c9f644f10ad683b02851730e6bc99fffb940aa5d/README.md#L21)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we update the copyright also?
</blockquote></details>

Forgot about it.
Will update it later on with other changes anyway.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/258)*

**Pull request merged**
