### PR TITLE
Test that AppShell is injectable

### PR DESCRIPTION
**Pull request by haijian-vaadin**
This is the test for https://github.com/vaadin/flow/pull/8876

### CODE REVIEW

**Review by Haprog — COMMENTED** [review]
Changes look ok to me, but there are test failures. I tried running the tests locally (after installing the related branch from linked flow PR) but it seems to always fail at:

```
[INFO] Reactor Summary for vaadin-spring-parent 14.0-SNAPSHOT:
[INFO] 
[INFO] vaadin-spring-parent ............................... SUCCESS [  0.288 s]
[INFO] vaadin-spring ...................................... SUCCESS [  7.553 s]
[INFO] Vaadin Spring tests ................................ SUCCESS [  0.319 s]
[INFO] Flow Spring Common UI components ................... SUCCESS [  0.854 s]
[INFO] Vaadin Spring Boot integration tests ............... SUCCESS [ 36.690 s]
[INFO] Vaadin Spring Boot integration tests with custom packages to scan SUCCESS [ 32.450 s]
[INFO] Vaadin Spring Boot deployable integration tests .... SUCCESS [ 35.033 s]
[INFO] Vaadin Spring Boot integration tests when deployed using a context path SUCCESS [ 30.169 s]
[INFO] Integration tests for V15+ endpoints ............... FAILURE [ 29.272 s]
[INFO] Integration tests for V15+ endpoints (custom Connect client) SKIPPED
[INFO] Keep this module as the last one in the list ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by Haprog** [comment]
I see:
```
[ERROR]   AppViewIT.setup:45 » NoSuchElement No element with tag <test-component> found ...
```
but before that there is:
```
java.lang.IllegalArgumentException: Unable to create an instance of 'com.vaadin.flow.connect.AppShell'. Make sure the class has a public no-arg constructor.
```
which seems like it may be related to this change.

**Comment by Haprog** [comment]
Do I need to do some change to pom.xml of the test module to test against correct version of Flow? Is the Flow change supposed to be cherry picked before we can get these tests passed or what's the procedure here?

**Comment by haijian-vaadin** [comment]
I merged the other PR to Flow, the PR depends on Flow 5.0-SNAPSHOT. I think now the tests shoul pass.

**Comment by haijian-vaadin** [comment]
Hi @Haprog , the test is now green? can I get approval?

**Review by Haprog — APPROVED** [review]

**Pull request merged**
