### PR TITLE
chore: Upgrade to Spring Boot 2.7.7

### PR DESCRIPTION
**Pull request by Artur-**
Spring Boot 2.5 and 2.6 are end of life

### CODE REVIEW

**Comment by mcollovati** [comment]
okhttp client version managed by spring conflicts with the one supported by the selenium version used in testbench 7.0.3
Upgrading testbench is not an option because base tests classes in Flow 9.0 uses 7.0.3 and there will be compilation errors.
Solution may be adding an entry for `com.squareup.okhttp3:okhttp:3.11.0`  in dependency management section oif `vaadin-spring-tests` module.

**Comment by mcollovati** [comment]
@Artur- is it ok to pin `okhttp3` in `vaadin-spring-tests module`?

**Comment by mcollovati** [comment]
@Artur- do you mind taking a look at the additional changes needed to upgrade to Spring Boot 2.7.7?

**Comment by Artur-** [comment]
Is the `spring.factories´ change the only one that explicitly makes it incompatible with earlier versions? If so, does it make sense to do it or just leave it use the deprecated variant "forever"?

**Comment by mcollovati** [comment]
> Is the `spring.factories´ change the only one that explicitly makes it incompatible with earlier versions? If so, does it make sense to do it or just leave it use the deprecated variant "forever"?

It seems so, other changes are all related to our tests.
I'll revert the `spring.factories` change

**Comment by Artur-** [comment]
👍  but I cannot approve my own PR

**Comment by mcollovati** [comment]
Thanks. I can approve it

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
