### PR TITLE
Exclude boot-stater for deploying

### PR DESCRIPTION
**Pull request by ZheSun88**
add another profile for deploying purpose;
add platform dependency to the project

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/301)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-spring-boot-starter/pom.xml, line 13 at r1](https://reviewable.io/reviews/vaadin/spring/301#-LD0mSZe4kfpvdfnVmZI:-LD0njEd93o4N1GJZXVX:bd4hqc1) ([raw file](https://github.com/vaadin/spring/blob/c293b5661ffdc6aec04c65d3e44d80e9e602a558/vaadin-spring-boot-starter/pom.xml#L13)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> <version>10.0-SNAPSHOT</version>
> ```

Isn't version defined in parent ?
Or the main idea to have it with  separate version ?


</blockquote></details>

this starter project will not release together with the parent, shouldnt it be a separate version?  otherwise, when we release this boot-starter, how can be set the version of it? can we do that by set the parent? 

---

*[vaadin-spring-boot-starter/pom.xml, line 20 at r1](https://reviewable.io/reviews/vaadin/spring/301#-LD0mYz-BWbpbnPc6WUs:-LD0o3yu5jIbT4DoPHj8:b-tlky7l) ([raw file](https://github.com/vaadin/spring/blob/c293b5661ffdc6aec04c65d3e44d80e9e602a558/vaadin-spring-boot-starter/pom.xml#L20)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> <vaadin.platform.version>10.0.0.beta10</vaadin.platform.version>
> ```

We still don't have snapshots for platform ?
Otherwise it should be snapshots.
</blockquote></details>

there was a problem with platform snapshot version. it looks that has been fixed now. Chnaged

---

*[vaadin-spring-boot-starter/pom.xml, line 41 at r1](https://reviewable.io/reviews/vaadin/spring/301#-LD0mw1x0desjq1VENE_:-LD0qewp1FRPlya8xWEB:bkeub7p) ([raw file](https://github.com/vaadin/spring/blob/c36a9ec2b65cce487fc1dca751c696dbcff0a7a2/vaadin-spring-boot-starter/pom.xml#L41)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-spring</artifactId>
>             <version>${project.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-html-components</artifactId>
>             <version>${vaadin.version}</version>
>         </dependency>
> ```


Both comes from the platform ?
</blockquote></details>

yes,  `vaadin-spring` https://github.com/vaadin/platform/blob/9fa5dbd06e04e3f2baf85cfcdc0a71d73ac6b109/vaadin-bom/pom.xml#L117

`flow-html-component` https://github.com/vaadin/platform/blob/9fa5dbd06e04e3f2baf85cfcdc0a71d73ac6b109/vaadin-bom/pom.xml#L160

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/301)*

**Comment by denis-anisimov** [comment]
Question about releasing:
at the moment we are releasing vaadin/spring as a whole.
As a result spring add-on is released together with the starter.

Are you going to change the way how spring add-on is released?
So perhaps instead of building spring repo we should do it separately for `vaadin-spring-boot-starter` and `vaadin-spring`.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spring-boot-starter/pom.xml, line 13 at r1](https://reviewable.io/reviews/vaadin/spring/301#-LD0mSZe4kfpvdfnVmZI:-LD0w7QU3jBvzZgp4aHk:b-ey7pr0) ([raw file](https://github.com/vaadin/spring/blob/c293b5661ffdc6aec04c65d3e44d80e9e602a558/vaadin-spring-boot-starter/pom.xml#L13)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

this starter project will not release together with the parent, shouldnt it be a separate version?  otherwise, when we release this boot-starter, how can be set the version of it? can we do that by set the parent? 
</blockquote></details>

You are right.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/301#-:-LD0wGUh7atI_J-0BZ4_:b-cxkdf1)*

**Comment by ZheSun88** [comment]
the main idea of this PR is following  https://github.com/vaadin/spring/issues/298, and Yes, after this change, we need to release the starter which depends on platform separately . But the `boot-starter` validation is still working as a whole package. I have added a separate configuration for `boot-starter` https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Release_VaadinSpringBootStarter. 

It looks we still need a separate step for the snapshot build. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/301#-:-LD0x3N-6k_nw7aQGZ_M:b-70f1s6)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/301#-:-LD0z1FM05OnxcjPt6NB:bnfp4nl)*

**Pull request merged**
