### PR TITLE
More spring data helpers

### PR DESCRIPTION
**Pull request by mstahv**
Played around with couple of extra helper, which are helpful in trivial bindings. And makes the demo code look even cooler 😂

Examples how it could look:

		grid.setItems(q -> repo.findAll(pageRequestOfQuery(q)).stream());
		
		grid.setItems(bindToRepository(repo));

The same code in my blog entry currently:

    grid.setItems(q -> repo.findAll(PageRequest.of(q.getPage(), q.getPageSize(),
          VaadinSpringDataHelpers.toSpringDataSort(q))).stream());

### CODE REVIEW

**Comment by mstahv** [comment]
We'd should try to write some tests fro these methods before merging, these are now only tested separately.

**Comment by mshabarov** [comment]
Hi @mstahv , I've added a few simple tests for helper methods and made some naming and javadoc improvements. Could you please review, when appropriate?

**Review by mstahv — COMMENTED** [review]
Looks good to me!

**Comment by mshabarov** [comment]
> Looks good to me!

Thanks! I'll merge it, as soon as we fix the problem in CI.

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
