### PR TITLE
Support using Spring beans in declarative file

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/193)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/VaadinConfiguration.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/spring/193#-KeCtCfdbxCe7QHnXHjo:-KeCtCfeO0TcOl37Wu_l:bczr1gr) ([raw file](https://github.com/vaadin/spring/blob/813f2f10ffc9e08e9bcabef701da743c406f6eb0/vaadin-spring/src/main/java/com/vaadin/spring/VaadinConfiguration.java#L89)):*
> ```Java
>             throws BeansException {
>         this.applicationContext = applicationContext;
>         Design.setComponentFactory(
> ```

What about injected factory? Is it springy - to use the hardcoded factory?

---

*[vaadin-spring/src/test/resources/com/vaadin/spring/internal/RootView.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/spring/193#-KeCt3fBZpRnsjkCotM2:-KeCt3fBZpRnsjkCotM3:be5n82v) ([raw file](https://github.com/vaadin/spring/blob/813f2f10ffc9e08e9bcabef701da743c406f6eb0/vaadin-spring/src/test/resources/com/vaadin/spring/internal/RootView.html#L14)):*
> ```HTML
>   </vaadin-vertical-layout>
>  </body>
> </html>
> ```

Missed new line (not a  blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/193)*

**Comment by Artur-** [comment]
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/VaadinConfiguration.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/spring/193#-KeCtCfdbxCe7QHnXHjo:-KfMMOQfQecksXBF15T8:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/813f2f10ffc9e08e9bcabef701da743c406f6eb0/vaadin-spring/src/main/java/com/vaadin/spring/VaadinConfiguration.java#L89)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What about injected factory? Is it springy - to use the hardcoded factory?
</blockquote></details>

Done.

---

*[vaadin-spring/src/test/resources/com/vaadin/spring/internal/RootView.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/spring/193#-KeCt3fBZpRnsjkCotM2:-KfMMPIyu6EzsYCkaKJW:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/813f2f10ffc9e08e9bcabef701da743c406f6eb0/vaadin-spring/src/test/resources/com/vaadin/spring/internal/RootView.html#L14)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Missed new line (not a  blocker)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/193)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r2.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/193#-:-KfUt1ieMog4iJP34KPY:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 7 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/193)*

**Pull request merged**
