### PR TITLE
test: Test uploads when using Spring Security

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by Legioth** [comment]
Shouldn't we instead change it so that `requestUtil::isFrameworkInternalRequest` also detects upload requests, rather than doing something specific to Spring Security?

**Comment by Artur-** [comment]
Maybe it could be considered an "internal request that is needed for the application to work"

**Comment by Artur-** [comment]
Depends on https://github.com/vaadin/flow/pull/11278 then

**Review by pleku — APPROVED** [review]

**Comment by pleku** [comment]
Will rerun the build once the flow snapshot build has finished.

**Pull request merged**
