### PR TITLE
Update README for 3.0

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/284)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/spring/284#-LATJ0kA-Ce6eaJ6ggg7:-LATJ0kA-Ce6eaJ6ggg8:b-i5ht67) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L7)):*
> ```Markdown
> 
> Vaadin Spring is the official Spring integration for [Vaadin Framework](https://github.com/vaadin/framework).
> This branch is Vaadin Framework V8.2 compatible. See other branches for other framework versions:
> ```

8.2+. There are already 8.3, 8.4 and 8.5 planned.

---

*[README.md, line 8 at r1](https://beta.reviewable.io/reviews/vaadin/spring/284#-LATJAfW8F9nESEHDHsr:-LATJAfW8F9nESEHDHss:brfv8z6) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L8)):*
> ```Markdown
> Vaadin Spring is the official Spring integration for [Vaadin Framework](https://github.com/vaadin/framework).
> This branch is Vaadin Framework V8.2 compatible. See other branches for other framework versions:
> * 1.2 for Vaadin Framework V7 versions 
> ```

Better to reverse  the order: Latest at the top. 
And it looks confusing without 3.0.0 in the list

I'd add
'* 3.0 for Vaadin 8.2+

---

*[README.md, line 9 at r1](https://beta.reviewable.io/reviews/vaadin/spring/284#-LATJfcVEnku7du-f1E8:-LATIBSi7xTYq8Qjypct:b99vv1e) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L9)):*
> ```Markdown
> This branch is Vaadin Framework V8.2 compatible. See other branches for other framework versions:
> * 1.2 for Vaadin Framework V7 versions 
> * 2.0 and 2.1 for Vaadin Framework V8.0.X versions 
> ```

8.0...8.1

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/284)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/spring/284)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 7 at r1](https://reviewable.io/reviews/vaadin/spring/284#-LATJ0kA-Ce6eaJ6ggg7:-LCn1XYj4DdSSZXhMW8j:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L7)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

8.2+. There are already 8.3, 8.4 and 8.5 planned.
</blockquote></details>

Done.

---

*[README.md, line 8 at r1](https://reviewable.io/reviews/vaadin/spring/284#-LATJAfW8F9nESEHDHsr:-LCn1JcS26mT0p6aCsRM:bvx08of) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L8)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Better to reverse  the order: Latest at the top. 
And it looks confusing without 3.0.0 in the list

I'd add
'* 3.0 for Vaadin 8.2+
</blockquote></details>

This is about `3.0` for `8.2+`. And the text above says ` See other branches for other framework versions`.

_other_

So for me it's confusing.
But done.

---

*[README.md, line 9 at r1](https://reviewable.io/reviews/vaadin/spring/284#-LATJfcVEnku7du-f1E8:-LCn1X0oBCB8CQNaVmKx:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/f61a3ecf170ab5ad627dbd6c4e63d562b6515cf2/README.md#L9)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

8.0...8.1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/284)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/284)*

**Pull request merged**
