### PR TITLE
Basic Spring Security support

### LINKED ISSUE #217: vaadin-spring-parent release 2.0.0 contains SNAPSHOT versions
## vaadin-spring-parent
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-spring-parent</artifactId>
    <version>2.0.0</version>
    <packaging>pom</packaging>

<!-- These are typically overridden with BOMs -->
        <vaadin.version>8.0-SNAPSHOT</vaadin.version>

.....
```
## My pom.xml contains below:

```xml
<properties>
		<vaadin.version>8.0.0</vaadin.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

<dependencies>

		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
		</dependency>

...
```

With above, I still see maven trying to pull 8.0-SNAPSHOT version of vaadin-server.
It proves that below doesn't work:
```xml
<!-- These are typically overridden with BOMs -->
        <vaadin.version>8.0-SNAPSHOT</vaadin.version>
```

Is there any quick fix?

### PR DESCRIPTION
**Pull request by elmot**
Fixes #217 as well

This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/219)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-spring-security/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhBn-D7s7rOaclRms:-KmfhBn-D7s7rOaclRmt:brblfal) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L15)):*
> ```XML
>     <name>vaadin-spring-security</name>
>     <description>
>         Provides Spring integration for Vaadin applications.
> ```

(this could be updated)

---

*[vaadin-spring-security/pom.xml, line 114 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhDNl8-JIMwNFNxZr:-KmfhDNl8-JIMwNFNxZs:bppwt1k) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L114)):*
> ```XML
>                     <execution>
>                         <goals>
>                             <goal>test-jar</goal>
> ```

(why do we need a test JAR?)

---

*[vaadin-spring-security/pom.xml, line 120 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhJoKUtZY9l3CBnGV:-KmfhJoLnwbWBsYeQVx7:btjv1ek) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L120)):*
> ```XML
>             </plugin>
>         </plugins>
>     </build>    
> ```

trailing whitespace

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-Kmfj3C9WcwYddWNKnw3:-Kmfj3C9WcwYddWNKnw4:bxzgmtr) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java#L34)):*
> ```Java
>  * {@link com.vaadin.spring.annotation.SpringComponent @SpringComponent} annotation and be visible for component scan.
>  * <p>
>  * If the implementor of the class is used, application {@link View Views} can be protected against unauthorized access with
> ```

"the implementor" -> "an implementation"?
... with the {@link Secured @Secured} annotation

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfiuUbA4anP6DWaUMI:-KmfiuUbA4anP6DWaUMJ:b-z0oe6c) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java#L89)):*
> ```Java
>      * Checks the security attributes found for a view for the current user
>      *
>      * @param ui                              current UI
> ```

lots of whitespace here?

---

*[vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfiLFJN5bOwOaiF1W9:-KmfiLFJN5bOwOaiF1WA:bxhkbal) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L34)):*
> ```Java
>         SecurityContext context = SecurityContextHolder.getContext();
>         Authentication authentication = context.getAuthentication();
>         if(authentication==null) return false;
> ```

formatting conventions: braces and separate line for return

---

*[vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfijuoyXdzx49R4k1B:-KmfijuoyXdzx49R4k1C:bmxzl3g) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L38)):*
> ```Java
>         for (GrantedAuthority authority : authorities) {
>             for (String attribute : securityConfigurationAttributes) {
>                 if (authority.getAuthority().contains(attribute)) {
> ```

(not production safe code IMO as based on String.contains(), but probably ok for the test)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by elmot** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring-security/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhBn-D7s7rOaclRms:-Kmg11DRxTv0FeWueWTo:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L15)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this could be updated)
</blockquote></details>

Done.

---

*[vaadin-spring-security/pom.xml, line 114 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhDNl8-JIMwNFNxZr:-Kmg11cf2zB8U8GGU8HY:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L114)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(why do we need a test JAR?)
</blockquote></details>

Done.

---

*[vaadin-spring-security/pom.xml, line 120 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfhJoKUtZY9l3CBnGV:-Kmg1CLQ04b9DY5XMeM8:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/pom.xml#L120)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

trailing whitespace
</blockquote></details>

Done.

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-Kmfj3C9WcwYddWNKnw3:-Kmg1PaH9yvildJhdTAW:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"the implementor" -> "an implementation"?
... with the {@link Secured @Secured} annotation
</blockquote></details>

Done.

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfiuUbA4anP6DWaUMI:-Kmg1p9m3Z_MDI8qOEki:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/main/java/com/vaadin/spring/access/AbstractSecuredViewAccessControl.java#L89)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

lots of whitespace here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by elmot** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfiLFJN5bOwOaiF1W9:-Kmg2qia_k4HCGGbmAp5:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

formatting conventions: braces and separate line for return
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by elmot** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/spring/219#-KmfijuoyXdzx49R4k1B:-Kmkmn_2__dRRcNG86Ix:b8wcada) ([raw file](https://github.com/vaadin/spring/blob/db31666c861012da8bb8bdc44d531b988583aaae/vaadin-spring-security/src/test/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not production safe code IMO as based on String.contains(), but probably ok for the test)
</blockquote></details>

Removed completely, done for production class with quality

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3, 2 of 4 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-spring-security/pom.xml, line 39 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-KmktG59n9vovZlMvdqw:-KmktG5Ar_gHjH15SjPa:bgv0c5t) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/pom.xml#L39)):*
> ```XML
>             <artifactId>spring-security-web</artifactId>
>             <version>${spring.security.version}</version>
>             <scope>provided</scope>
> ```

these should probably be in the default scope now that this is a separate module

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-KmkvGEwl9-FTF4vMlFr:-KmkvGEwl9-FTF4vMlFs:b-yvteen) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L49)):*
> ```Java
>     private WebApplicationContext webApplicationContext;
> 
>     protected boolean isAccessGranted(UI ui, String[] securityConfigurationAttributes) {
> ```

Does this method actually need the UI?
(also this method could have a bit of javadoc)

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 57 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-Kmkw9-i6ylRccVH-n8Q:-Kmkw9-i6ylRccVH-n8R:b-fed4zz) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L57)):*
> ```Java
>         Set<String> authorities = authentication.getAuthorities().stream()
>                 .map(GrantedAuthority::getAuthority)
>                 .collect(Collectors.toSet());
> ```

(Why not just use anyMatch(Predicate)? Or would it lead to much more complicated code?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by elmot** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-spring-security/pom.xml, line 39 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-KmktG59n9vovZlMvdqw:-Kmz4NvJkb9pHg2d0L9I:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/pom.xml#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

these should probably be in the default scope now that this is a separate module
</blockquote></details>

Done.

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-KmkvGEwl9-FTF4vMlFr:-KmzS_8kHijcuXiKM9H2:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L49)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this method actually need the UI?
(also this method could have a bit of javadoc)
</blockquote></details>

Done.

---

*[vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java, line 57 at r4](https://reviewable.io:443/reviews/vaadin/spring/219#-Kmkw9-i6ylRccVH-n8Q:-KmzSa72NHVFVMk4zuRE:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/d8852a51959383e0182a1563e049a30713fa5a30/vaadin-spring-security/src/main/java/com/vaadin/spring/access/SecuredViewAccessControl.java#L57)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Why not just use anyMatch(Predicate)? Or would it lead to much more complicated code?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spring-security/pom.xml, line 49 at r6](https://reviewable.io:443/reviews/vaadin/spring/219#-KnYQfGKOKlohBjk82yB:-KnYQfGKOKlohBjk82yC:bqv4l27) ([raw file](https://github.com/vaadin/spring/blob/e941a753c9455323bde5b8be164eefc60800c941/vaadin-spring-security/pom.xml#L49)):*
> ```XML
>             <artifactId>spring-security-config</artifactId>
>             <version>${spring.security.version}</version>
>             <scope>provided</scope>
> ```

still provided?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/219#-:-KnYxVCRfHviA0-KQj0J:bnfp4nl)*

**Pull request merged**
