### PR TITLE
Workaround for new static resource handling in Vaadin 8

### PR DESCRIPTION
**Pull request by elmot**
Fixes vaadin/framework8-issues#445

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/155)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXXEGOlOPyFEb_X-LS:-KWXXEGOlOPyFEb_X-LT:b-k8z5l8) (no related file):*
Validation test is needed.
Is it possible to provide it here or we should include it into FW itself ?

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXX3O6eCbW0tl4QhFX:-KWXX3O7maiGL1QIlsuW:b-y5rlge) ([raw file](https://github.com/vaadin/spring/blob/1153c8ca8fb43067382d1b35f10ce9f424008b7e/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L157)):*
> ```Java
>             try {
>                 String decodedRequestURI = URLDecoder.decode(
>                         request.getRequestURI(), "UTF-8");
> ```

The add-on should work with J6 I guess? 
That's why "UTF-8" is hardcoded ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXiluLnzCM9q1FUcnW:-KWXiluLnzCM9q1FUcnX:bc8siwh) (no related file):*
Why is this workaround needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXiluLnzCM9q1FUcnW:-KWXk5-dsoL1G2acjFUx:b-9zk09o) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Why is this workaround needed?
</details>
Something is required https://github.com/vaadin/framework8-issues/issues/445.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXiluLnzCM9q1FUcnW:-KWXll1x_aWHQ9m5nuU2:b-62z1r) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary>
> Something is required https://github.com/vaadin/framework8-issues/issues/445.
</details>
The root cause is that our Spring Boot integration does some hacky things to be able to serve static files without causing incompatibilities with Spring MVC. This manifests itself as static resource requests without `VAADIN` in neither `getServletPath()` nor in `getPathInfo()`.

Approaches for fixing this would be to either look for `VAADIN` in the original request URI or to make sure requests are dispatched in a way that is consistent with the servlet specification.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXXEGOlOPyFEb_X-LS:-KWXxG3aZk_u0Kh4UO9z:bup3tqf) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary>
> Validation test is needed.
> Is it possible to provide it here or we should include it into FW itself ?
</details>
We have the test for this in framework8-demo, and also we have a ticket vaadin/framework8-issues#454
Let's do additional research and testing there.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXX3O6eCbW0tl4QhFX:-KWXx3zrHlBnSWoF_-AU:bbps5ye) ([raw file](https://github.com/vaadin/spring/blob/1153c8ca8fb43067382d1b35f10ce9f424008b7e/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L157)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary>
> The add-on should work with J6 I guess? 
> That's why "UTF-8" is hardcoded ?
</details>
Good point. The whole branch is switched to java 8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXXEGOlOPyFEb_X-LS:-KWXyO-X9FcALKfFJTWG:b-wx5qij) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> We have the test for this in framework8-demo, and also we have a ticket vaadin/framework8-issues#454
> Let's do additional research and testing there.
</details>
Demos are not really useful for FW validation: they are not rebuilt each time when FW changes. That's why we have troubles all the time with demos right now.
So we need a test either here in this project for this or in the FW itself so that we can detect failure immediately once it's introduced.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXX3O6eCbW0tl4QhFX:-KWXyDBHy80qwtkfR8WO:bc2ffqw) ([raw file](https://github.com/vaadin/spring/blob/1153c8ca8fb43067382d1b35f10ce9f424008b7e/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L157)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Good point. The whole branch is switched to java 8
</details>
But this one is still hardcoded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXX3O6eCbW0tl4QhFX:-KWXzGVQ7cswcDCo6TuJ:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1153c8ca8fb43067382d1b35f10ce9f424008b7e/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L157)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary>
> But this one is still hardcoded.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXiluLnzCM9q1FUcnW:-KWYPvZfIrD38cGsYGa4:b-62f49u) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> The root cause is that our Spring Boot integration does some hacky things to be able to serve static files without causing incompatibilities with Spring MVC. This manifests itself as static resource requests without `VAADIN` in neither `getServletPath()` nor in `getPathInfo()`.
> 
> Approaches for fixing this would be to either look for `VAADIN` in the original request URI or to make sure requests are dispatched in a way that is consistent with the servlet specification.
</details>
Note this change is not going to be included into vaadin-spring for vaadin 7 anyway, that is only for vaadin 8.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
The pull request became really huge after rebasing on top of vaadin-spring v.1.1.0
Sorry for that.

---

Review status: 0 of 68 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXXEGOlOPyFEb_X-LS:-KWc2aSmvflW8VK05VsH:blvhv8z) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary>
> Demos are not really useful for FW validation: they are not rebuilt each time when FW changes. That's why we have troubles all the time with demos right now.
> So we need a test either here in this project for this or in the FW itself so that we can detect failure immediately once it's introduced.
</details>
Added real web test to vaadin-spring-boot-starter project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155#-:-KWc303uY7DDjnPuqLJC:byezcov)*

**Comment by Legioth** [comment]
Review status: 0 of 68 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 152 at r5](https://reviewable.io:443/reviews/vaadin/spring/155#-KWcDOEGpQCxYpzFRvHt:-KWcDOEGpQCxYpzFRvHu:b-sl8j62) ([raw file](https://github.com/vaadin/spring/blob/78da0920154bd0b03c8345d7b168a6832def0a71/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L152)):*
> ```Java
> 
>     @Override
>     protected String getStaticFilePath(HttpServletRequest request) {
> ```

Add a comment that describes why this is necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by Legioth** [comment]
Review status: 0 of 68 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/155#-KWXiluLnzCM9q1FUcnW:-KWcDTFZTS7rHxqv8fAS:b-q5lw5g) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Note this change is not going to be included into vaadin-spring for vaadin 7 anyway, that is only for vaadin 8.
</details>
This approach still moves things in a better direction, even though it could probably be further improved by actually attacking the root cause.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by denis-anisimov** [comment]
Reviewed 68 of 68 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
Review status: 67 of 68 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 152 at r5](https://reviewable.io:443/reviews/vaadin/spring/155#-KWcDOEGpQCxYpzFRvHt:-KWgMiMWL-MPiS2eGL9-:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/78da0920154bd0b03c8345d7b168a6832def0a71/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L152)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> Add a comment that describes why this is necessary
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by Legioth** [comment]
Review status: 67 of 68 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 152 at r5](https://reviewable.io:443/reviews/vaadin/spring/155#-KWcDOEGpQCxYpzFRvHt:-KWhWneOLurTObWNX5x5:b-1xlacu) ([raw file](https://github.com/vaadin/spring/blob/78da0920154bd0b03c8345d7b168a6832def0a71/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L152)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Done.
</details>
This comment tells a lot of things about various things, but nothing about why this needs to be implemented in the way it is.

The thing I think someone needs to know when they look at this code is the fact that `VaadinServletConfiguration` uses `DispatcherServlet` in way that makes the `VAADIN` part to not be present in `getPathInfo()`nor in `getServletPath()`, and therefore it's necessary to manually decode `getRequestURI()` instead. 

That information is actually more of an implementation detail and probably not appropriate as a javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by elmot** [comment]
Review status: 67 of 68 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java, line 152 at r5](https://reviewable.io:443/reviews/vaadin/spring/155#-KWcDOEGpQCxYpzFRvHt:-KWi0CtBMmz4YBMdDFlB:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/78da0920154bd0b03c8345d7b168a6832def0a71/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringVaadinServlet.java#L152)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>
> This comment tells a lot of things about various things, but nothing about why this needs to be implemented in the way it is.
> 
> The thing I think someone needs to know when they look at this code is the fact that `VaadinServletConfiguration` uses `DispatcherServlet` in way that makes the `VAADIN` part to not be present in `getPathInfo()`nor in `getServletPath()`, and therefore it's necessary to manually decode `getRequestURI()` instead. 
> 
> That information is actually more of an implementation detail and probably not appropriate as a javadoc.
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/155)*

**Pull request closed without merging**
