### PR TITLE
Support for VaadinServiceInitListeners

### PR DESCRIPTION
**Pull request by berndhopp**
This PR aims to bring support for VaadinServiceInitListeners

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/218)

### CODE REVIEW

**Comment by hesara** [comment]
This seems to have been made with a committer id (e-mail) that is not linked to a GH account, and thus the CLA check fails. Bernd, could you add the e-mail you used in the commit to your GH account or create a new PR with the correct account in the commit, and then sign the CLA.

**Comment by hesara** [comment]
:lgtm: but we need CLA to be able to merge this - @berndhopp please update the committer field or add that e-mail to your GH account and click the CLA button

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/218#-:-KnYu-HN1OOLRKjQEWDG:b-pm77c)*

**Comment by Legioth** [comment]
Since Bern is a Vaadin employee, I think we can temporarily disable the CLA requirement for submitting this PR.

**Comment by berndhopp** [comment]
should be mergeable now

**Pull request merged**
