### PR TITLE
Fix Spring UI paths with PushState based navigation

### PR DESCRIPTION
**Pull request by tsuoanttila**
Automatically use wildcard paths for UIs with PushStateNavigation annotation

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/238)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spring/238#-KzOMaCTGnJQxQac19Yu:-KzOMaCTGnJQxQac19Yv:bfzhl2b) (no related file):*
Needs a discussion on the versioning and release. This is depending on 8.2, not 8.0.6 like the old pom.xml defined it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by caalador** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by Darsstar** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 161 at r3](https://reviewable.io:443/reviews/vaadin/spring/238#-KziOAWqWoQ8OySCJ_Ks:-KziOAWrdtRY2OcUzlsY:bxt2bbe) ([raw file](https://github.com/vaadin/spring/blob/1e26a4362e71e11d451f255c068dcfebf103f811/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L161)):*
> ```Java
>         // Pass the path info to the UI through request
>         uiClassSelectionEvent.getRequest()
>                 .setAttribute(ApplicationConstants.UI_ROOT_PATH, pathInfo);
> ```

I think UI_ROOT_PATH should be prefixed with a slash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by tsuoanttila** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 161 at r3](https://reviewable.io:443/reviews/vaadin/spring/238#-KziOAWqWoQ8OySCJ_Ks:-KzxHgjNNVeECFMSprmc:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1e26a4362e71e11d451f255c068dcfebf103f811/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L161)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

I think UI_ROOT_PATH should be prefixed with a slash.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by Darsstar** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 150 at r1](https://reviewable.io:443/reviews/vaadin/spring/238#-KzxhJMFaj30FbOrk0tM:-KzxhJMGmW_eStDCfSwr:b-ya0wdz) ([raw file](https://github.com/vaadin/spring/blob/be3ce17dceb562392dc0632a31905a72ed06ff26/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L150)):*
> ```Java
>         } else {
>             for (Map.Entry<String, Class<? extends UI>> entry : wildcardPathToUIMap
>                     .entrySet()) {
> ```

Similar to the CDI plugin, sorting this by the length of the key so that the most specific path matches is probably desirable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 150 at r1](https://reviewable.io:443/reviews/vaadin/spring/238#-KzxhJMFaj30FbOrk0tM:-Kzxn5zBLnzFSwE6vfbV:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/be3ce17dceb562392dc0632a31905a72ed06ff26/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L150)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

Similar to the CDI plugin, sorting this by the length of the key so that the most specific path matches is probably desirable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by Darsstar** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by denis-anisimov** [comment]
Looks OK.
Only minor code improvements.

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 4 of 5 files at r3, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 106 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-ordnA8SVwriEHBlog:-L-ordnA8SVwriEHBloh:bqf3y1l) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L106)):*
> "/*"

`2` below is the length of this string.
I would suggest to extract the string as a constant and use its length instead of `2` below.
It makes the code clearer. 

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 108 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orpuCGFA1RSBwqFkH:-L-orpuCGFA1RSBwqFkI:b-8t991g) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L108)):*
> "/**"

same here

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 110 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orIbVbv7U_kdYXpyL:-L-orIbVbv7U_kdYXpyM:b7af1tg) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L110)):*
> String altPath = "/";
>  
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>                     // Map path without ending slash
>                     if (path.endsWith("/*")) {
>                         altPath += path.substring(0, path.length() - 2);
>                     } else if (path.endsWith("/**")) {
>                         altPath += path.substring(0, path.length() - 3);
>                     } else {
>                         // Map path with ending slash
>                         altPath += path + "/";
>                     }
</details>

I would suggest to extract this as a method with meaningful name to get the idea what's going on from its name.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 112 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orye44PIYfgbyYnjc:-L-orye44PIYfgbyYnjd:b-um63wg) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L112)):*
> altPath += path + "/";

Here and above: 
Let's use `StringBuilder` since there are many concatenation 

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 146 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-osO0-NrRbVFTFhAIj:-L-osO0-NrRbVFTFhAIk:b576ugu) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L146)):*
> "/*"

Constants from above will be used here and below.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 150 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-osE43UFlCQLV2bK1v:-L-osE43UFlCQLV2bK1w:b-k46d0g) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L150)):*
> // Map PushStateNavigation UIs to wildcard path
>             boolean hasPushStateNavigation = applicationContext
>                     .findAnnotationOnBean(uiBeanName,
>                             PushStateNavigation.class) != null;
>  
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>             if (hasPushStateNavigation) {
>                 if (path.endsWith("/*")) {
>                     path = path + "*";
>                 } else if (!path.endsWith("/**")) {
>                     path = path + "/**";
>                 }
>                 assert path.endsWith(
>                         "/**") : "PushStateNavigation UI Path should end with '/**'";
>             }
</details>

Please extract it as a separate method with a meaningful name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238#-:-L-otihngktmAIPr51J9:b-h3fuvg)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 106 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-ordnA8SVwriEHBlog:-L042UviQ3b4ynh3dxui:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L106)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "/*"

`2` below is the length of this string.
I would suggest to extract the string as a constant and use its length instead of `2` below.
It makes the code clearer. 
</blockquote></details>

Done.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 108 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orpuCGFA1RSBwqFkH:-L042Vus4G7Pb8cdXoql:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L108)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "/**"

same here
</blockquote></details>

Done.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 110 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orIbVbv7U_kdYXpyL:-L045Fw37yETDJwiwD_W:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L110)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> String altPath = "/";
>  
>                     // Map path without ending slash
>                     if (path.endsWith("/*")) {
>                         altPath += path.substring(0, path.length() - 2);
>                     } else if (path.endsWith("/**")) {
>                         altPath += path.substring(0, path.length() - 3);
>                     } else {
>                         // Map path with ending slash
>                         altPath += path + "/";
>                     }

I would suggest to extract this as a method with meaningful name to get the idea what's going on from its name.
</blockquote></details>

Done.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 112 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-orye44PIYfgbyYnjc:-L045GL87c3wEuW_jOWm:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L112)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> altPath += path + "/";

Here and above: 
Let's use `StringBuilder` since there are many concatenation 
</blockquote></details>

Done.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 146 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-osO0-NrRbVFTFhAIj:-L044ckUigALsZDmp3xE:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L146)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "/*"

Constants from above will be used here and below.
</blockquote></details>

Done.

---

*[vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java, line 150 at r6](https://reviewable.io:443/reviews/vaadin/spring/238#-L-osE43UFlCQLV2bK1v:-L045Ecyr9HxaXGYDHxg:b-896fix) ([raw file](https://github.com/vaadin/spring/blob/1b7d784fec30101ad02d89abff8b5139445cd74b/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L150)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // Map PushStateNavigation UIs to wildcard path
>             boolean hasPushStateNavigation = applicationContext
>                     .findAnnotationOnBean(uiBeanName,
>                             PushStateNavigation.class) != null;
>  
>             if (hasPushStateNavigation) {
>                 if (path.endsWith("/*")) {
>                     path = path + "*";
>                 } else if (!path.endsWith("/**")) {
>                     path = path + "/**";
>                 }
>                 assert path.endsWith(
>                         "/**") : "PushStateNavigation UI Path should end with '/**'";
>             }

Please extract it as a separate method with a meaningful name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/238)*

**Pull request merged**
