### PR TITLE
Support ViewContainer annotation on classes and beans

### LINKED ISSUE #113: ViewContainer annotations on multiple UIs cause a conflict to be reported
If multiple UI classes have the @ViewContainer annotation, an exception about multiple ViewContainers is thrown. The ViewContainers of different UIs should not cause conflicts.

This should apply both to @ViewContainer on beans and @ViewContainer on fields.

### PR DESCRIPTION
**Pull request by hesara**
Closes #113 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/118)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMq-oMVCycspMtlWug:-KUMq-oMVCycspMtlWuh:btkquk9) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java#L55)):*
> ```Java
> 
>     @Override
>     public Object postProcessAfterInitialization(final Object bean,
> ```

It *might* make sense to move this to   postProcessBeforeInitialization()

---

*[vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java, line 117 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMoRcWMp0aS7aXkiGG:-KUMoRcWMp0aS7aXkiGH:b-eoltuv) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java#L117)):*
> ```Java
>         builder.setScope(UIScopeImpl.VAADIN_UI_SCOPE_NAME);
>         builder.setRole(BeanDefinition.ROLE_SUPPORT);
>         AbstractBeanDefinition beanDefinition = builder.getBeanDefinition();
> ```

It *might* be useful
        beanDefinition.setOriginatingBeanDefinition(<field declaration bean class definition>);
        beanDefinition.setSource(<field declaration bean class definition>);

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 263 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMs4qdyKQMpL-mo6mF:-KUMs4qe6uaOF8wzy8cC:b-xndiyd) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L263)):*
> ```Java
> 
>     protected Object findViewContainer(UI ui) {
>         try {
> ```

for now, maybe it is better to only support @ViewContainer on the UI class, its members or on beans

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 270 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMsJmM1cs_PG5FofRJ:-KUMsJmM1cs_PG5FofRK:bsm6zv) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L270)):*
> ```Java
>         } catch (NoUniqueBeanDefinitionException e) {
>             throw e;
>         } catch (NoSuchBeanDefinitionException e) {
> ```

UI's fields/methods to be scanned as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/118)*

**Comment by elmot** [comment]
Reviewed 3 of 7 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 299 at r2](https://reviewable.io:443/reviews/vaadin/spring/118#-KUQjhQI1s9R__TK49rS:-KUQjhQI1s9R__TK49rT:bki2a3i) ([raw file](https://github.com/vaadin/spring/blob/289193a3448ce7b0c2d09fba9386015648f9791c/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L299)):*
> ```Java
>         } catch (NoUniqueBeanDefinitionException e) {
>             logger.error(
>                     "Multiple " + ViewContainerPostProcessor.class.getName()
> ```

The diagnostics is misleading for an application developer.The do not know about  ViewContainerPostProcessors. Let's not assume the diagnostic here is only for vaadin developers

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 305 at r2](https://reviewable.io:443/reviews/vaadin/spring/118#-KUQr6irTyU93IBHwG_i:-KUQr6irTyU93IBHwG_j:b-34vmyd) ([raw file](https://github.com/vaadin/spring/blob/289193a3448ce7b0c2d09fba9386015648f9791c/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L305)):*
> ```Java
>             // This is somewhat noisy as potentially logged for every UI
>             // created.
>             logger.info(ViewContainerPostProcessor.class.getName()
> ```

See above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/118)*

**Comment by hesara** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMq-oMVCycspMtlWug:-KURsgZBYmzICicEp2qp:bjfc0fx) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java#L55)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> It *might* make sense to move this to   postProcessBeforeInitialization()
</details>
that does not work when @ViewContainer is used on a factory method

---

*[vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java, line 117 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMoRcWMp0aS7aXkiGG:-KURtlvIiyqFHc-nD69d:bbj8vzo) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/internal/ViewContainerPostProcessor.java#L117)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> It *might* be useful
>         beanDefinition.setOriginatingBeanDefinition(<field declaration bean class definition>);
>         beanDefinition.setSource(<field declaration bean class definition>);
> 
</details>
These are not available through the builder, only in the beanDefinition, and not well documented. Furthermore, they are configuration mechanism specific. Right now, I'd omit these and only add if needed later unless you can tell why each of these would be needed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 263 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMs4qdyKQMpL-mo6mF:-KURueFIm9zWXnX9-FCD:btpq213) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L263)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> for now, maybe it is better to only support @ViewContainer on the UI class, its members or on beans
</details>
I don't see the need for the restriction in the basic case (based on VCRB) now that field scanning is not performed

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 270 at r1](https://reviewable.io:443/reviews/vaadin/spring/118#-KUMsJmM1cs_PG5FofRJ:-KURus-NQyNMpRtzBR7m:bwyyfi2) ([raw file](https://github.com/vaadin/spring/blob/edb4c9cffdcc9374ca0aead0a2a01c9da914f253/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L270)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> UI's fields/methods to be scanned as well
</details>
fields and (non-configuration) methods are not supported at the moment, so I don't see the need for that right now

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 299 at r2](https://reviewable.io:443/reviews/vaadin/spring/118#-KUQjhQI1s9R__TK49rS:-KURwfftaoWTGSawIeQ3:b-65kha7) ([raw file](https://github.com/vaadin/spring/blob/289193a3448ce7b0c2d09fba9386015648f9791c/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L299)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> The diagnostics is misleading for an application developer.The do not know about  ViewContainerPostProcessors. Let's not assume the diagnostic here is only for vaadin developers
</details>
IMO this can only occur if the application developer has explicitly declared beans of type VCPP, so the error message is appropriate for those who can see it.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 305 at r2](https://reviewable.io:443/reviews/vaadin/spring/118#-KUQr6irTyU93IBHwG_i:-KURwx7hSARfTBPn5Ikg:byr4ffv) ([raw file](https://github.com/vaadin/spring/blob/289193a3448ce7b0c2d09fba9386015648f9791c/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L305)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> See above
</details>
see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/118)*

**Comment by elmot** [comment]
Reviewed 1 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/118)*

**Pull request merged**
