### PR TITLE
chore: update spring-boot to 2.6.2

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by Artur-** [comment]
Fails in `test-ts-services ` with
```
[14:54:37] :	 [Step 3/7] 2021-11-29 12:54:37.103  WARN 5606 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
```

**Comment by platosha** [comment]
> Fails in `test-ts-services ` with
> 
> ```
> [14:54:37] :	 [Step 3/7] 2021-11-29 12:54:37.103  WARN 5606 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
> ```

Seems that we need to support the PathPattern based mapping to fix this, here is the PR https://github.com/vaadin/flow/pull/12474

**Comment by Artur-** [comment]
The next problem seems to be
```
java.lang.AbstractMethodError: Receiver class org.springframework.boot.web.servlet.filter.ErrorPageSecurityFilter does not define or inherit an implementation of the resolved method 'abstract void init(javax.servlet.FilterConfig)' of interface javax.servlet.Filter.
```

when running the app as a war using `jetty:run`

**Comment by Artur-** [comment]
https://github.com/spring-projects/spring-boot/issues/28854

**Review by caalador — APPROVED** [review]

**Pull request merged**
