### PR TITLE
Automatically configure navigator based on @ViewContainer bean

### LINKED ISSUE #86: Create @ViewContainer annotation
Create and document a ViewContainer annotation that can be used on classes.

### LINKED ISSUE #88: Auto-configure Navigator if there is a bean with @ViewContainer
Instantiate and initialize a Navigator using SpringViewProvider for the current UI if there is a bean implementing SingleComponentContainer, ComponentContainer or ViewDisplay with @ViewContainer annotation.

### PR DESCRIPTION
**Pull request by hesara**
Add a ViewContainer annotation and automatic configuration of navigation based on it.

This version does not automatically create SpringNavigator beans.

Closes #86
Closes #88

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/98)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/navigator/SpringNavigator.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTndSMKQR1yRLuF1MgD:-KTndSMKQR1yRLuF1MgE:b-bojp32) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/navigator/SpringNavigator.java#L35)):*
> ```Java
>  */
> @UIScope
> public class SpringNavigator extends Navigator {
> ```

Should be documented. Might be we need a separate ticket for documentation of everything at once.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 231 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTncF9MAOMdtn7NQu-p:-KTncF9MAOMdtn7NQu-q:bdnpj4l) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L231)):*
> ```Java
>                 .getBeanNamesForType(SpringNavigator.class);
>         if (beanNames.length > 0) {
>             if (beanNames.length > 1) {
> ```

Unnecessary if depth. Might be linear if-else or even switch..case..default

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 232 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTncQblEkmbV2boFtXk:-KTncQblEkmbV2boFtXl:biib91g) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L232)):*
> ```Java
>         if (beanNames.length > 0) {
>             if (beanNames.length > 1) {
>                 logger.warn("Multiple navigator beans defined");
> ```

Let's publish exact number or even full class list, that might make customer application debug much easier.
Throw an exception? working with multiple navigators might cause race condition,  since their order in list is nor guaranteed.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 249 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTndIlcAzOxdxl56VB_:-KTndIldf5FPFO4mI5lc:b-pwchls) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L249)):*
> ```Java
>         }
>         if (viewContainerBeanNames.length > 1) {
>             logger.error("Multiple view containers defined for the UI "
> ```

See my comment for Navigator beans

---

*[vaadin-spring/src/test/java/com/vaadin/spring/server/AbstractSpringUIProviderTest.java, line 65 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTne-iqrNzavyB5CnpN:-KTne-iqrNzavyB5CnpO:b-o23dkp) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/test/java/com/vaadin/spring/server/AbstractSpringUIProviderTest.java#L65)):*
> ```Java
> 
>         @Override
>         public VaadinSession createVaadinSession(VaadinRequest request)
> ```

What is the point of this method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/98)*

**Comment by hesara** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-spring/src/main/java/com/vaadin/spring/navigator/SpringNavigator.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTndSMKQR1yRLuF1MgD:-KTnnskph5sK5MOGDOAi:b-n3gzh7) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/navigator/SpringNavigator.java#L35)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Should be documented. Might be we need a separate ticket for documentation of everything at once.
</details>
added comments for the methods

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 231 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTncF9MAOMdtn7NQu-p:-KTreaL6hJ6_1UmAQ3Sw:b-2l7b3o) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L231)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Unnecessary if depth. Might be linear if-else or even switch..case..default
</details>
rewrote the whole method

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 232 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTncQblEkmbV2boFtXk:-KTreglOibI6-hrSorx1:b-nsbi0z) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L232)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Let's publish exact number or even full class list, that might make customer application debug much easier.
> Throw an exception? working with multiple navigators might cause race condition,  since their order in list is nor guaranteed.
</details>
rewrote the method (although in this particular case, the order IS guaranteed and we should actually use the last one if any)

---

*[vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java, line 249 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTndIlcAzOxdxl56VB_:-KTreu-zQFECz8PO5XSN:b-oy0ypy) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/main/java/com/vaadin/spring/server/SpringUIProvider.java#L249)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> See my comment for Navigator beans
</details>
logging names of all the conflicting beans

---

*[vaadin-spring/src/test/java/com/vaadin/spring/server/AbstractSpringUIProviderTest.java, line 65 at r2](https://reviewable.io:443/reviews/vaadin/spring/98#-KTne-iqrNzavyB5CnpN:-KTnm20_4MU2UhKaMyJX:bgbqt0m) ([raw file](https://github.com/vaadin/spring/blob/603c5beb204fa92b3b4559083b6747baf3ccbefe/vaadin-spring/src/test/java/com/vaadin/spring/server/AbstractSpringUIProviderTest.java#L65)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> What is the point of this method?
</details>
to make the method public for the tests to call it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/98)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/98#-:-KTrlJkRvumTP1Sx1Qyi:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 5 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/98)*

**Pull request merged**
