### PR TITLE
Travis has to use JDK 8 and be run over vaadin-8 branch

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/105)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 7 at r1](https://reviewable.io:443/reviews/vaadin/spring/105#-KTwziBaejpHoRak5MH_:-KTwziBaejpHoRak5MHa:b-bwadrx) ([raw file](https://github.com/vaadin/spring/blob/3c152e483b77abe8aee69bee70b36e48d9a3394b/.travis.yml#L7)):*
> ```YAML
> branches:
>   only:
>   - vaadin-8
> ```

does travis use this separately from each branch, with different configurations? if not, might not be able to make the change at the moment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/105)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 7 at r1](https://reviewable.io:443/reviews/vaadin/spring/105#-KTwziBaejpHoRak5MH_:-KU25O7tJ_hO98T6OM18:b1yfpfq) ([raw file](https://github.com/vaadin/spring/blob/3c152e483b77abe8aee69bee70b36e48d9a3394b/.travis.yml#L7)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> does travis use this separately from each branch, with different configurations? if not, might not be able to make the change at the moment
</details>
The only option to check is to merge the patch and check what happens

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/105)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring/105)*

**Comment by elmot** [comment]
Checked builds over both branches. They work

**Pull request merged**
