### PR TITLE
Make push url relative to context path

### PR DESCRIPTION
**Pull request by Artur-**
Fixes https://github.com/vaadin/flow/issues/4123

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/309)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/309#-:-LD-yboMAi1fx3gf-erl:bnfp4nl)*

**Comment by caalador** [comment]
Lots of failing tests.

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-spring-tests/test-spring-boot-contextpath/pom.xml, line 76 at r2](https://reviewable.io/reviews/vaadin/spring/309#-LDFk9PS9AybfrOjg7VB:-LDFk9PT7UcktCb8d_EI:b-ax0nw6) ([raw file](https://github.com/vaadin/spring/blob/a9bac836b4586b7557fec2afab7a2dded86e665e/vaadin-spring-tests/test-spring-boot-contextpath/pom.xml#L76)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 <exclusion>
>                     <groupId>org.springframework.boot</groupId>
>                     <artifactId>spring-boot-starter-tomcat</artifactId>
>                 </exclusion>
> ```
</details>



Not blocking. Just curious : what's the need for it ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/309#-:-LDFkLeu9ArzeEyPDieA:bnfp4nl)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[vaadin-spring-tests/test-spring-boot-contextpath/pom.xml, line 76 at r2](https://reviewable.io/reviews/vaadin/spring/309#-LDFk9PS9AybfrOjg7VB:-LDFkeFp0IUMu-tucKHv:b-iih3t7) ([raw file](https://github.com/vaadin/spring/blob/a9bac836b4586b7557fec2afab7a2dded86e665e/vaadin-spring-tests/test-spring-boot-contextpath/pom.xml#L76)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>                 <exclusion>
>                     <groupId>org.springframework.boot</groupId>
>                     <artifactId>spring-boot-starter-tomcat</artifactId>
>                 </exclusion>
> ```


Not blocking. Just curious : what's the need for it ?
</blockquote></details>

Not exactly sure. Some other modules also use Jetty instead of Tomcat. 

If you use Tomcat here, or seemingly if you use it in multiple modules, then starting Tomcat in the second module that is run will fail with 
```
Caused by: java.lang.Error: factory already defined
at java.net.URL.setURLStreamHandlerFactory(URL.java:1112) ~[na:1.8.0_161]
at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
```

Either it is run inside the same JVM instance or something else strange happens. With Jetty there are no such problems

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/spring/309)*

**Pull request merged**
